//=========================================================
// src/Meat_Curer_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8SB1_Register_Enums.h>                  // SFR declarations
#include <si_toolchain.h>
#include "InitDevice.h"
#include "retargetserial.h"
#include "smbus.h"
// $[Generated Includes]
// [Generated Includes]$

//Function Prototype//
unsigned int delay(long x);
unsigned int compDelay(int u);
void UpdateCurrentMeasurement(void);

//Structure Defines//
typedef struct LOG_T {
	int16_t celsiusTemperature;
	uint16_t percentHumidity;
} LOG;

//Global Variables//
LOG currentMeasurement;

//-----------------------------------------------------------------------------
// Pin Definitions
//-----------------------------------------------------------------------------
SI_SBIT(LED0, SFR_P1, 1);// '0' means ON, '1' means OFF
SI_SBIT(COMP, SFR_P1, 0);// '0' means ON, '1' means OFF

SI_SBIT(SDA, SFR_P1, 2);//I2C SDA line
SI_SBIT(SCL, SFR_P1, 3);//I2C SDA line

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {

}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {

	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();
	SCON0_TI = 1;	//Enable TX for UART

	ResetSensor();
	printf("Humidity Temperature Sensor Reset! \n\r");

	while (1) {
// $[Generated Run-time code]
// [Generated Run-time code]$
		/*LED0 = 1;
		COMP = 1;
		printf("Compressor On! \r\n");
		UpdateCurrentMeasurement();
		printf("Humidity is: %u\r\n", currentMeasurement.percentHumidity);
		printf("Temperature is: %u\r\n", currentMeasurement.celsiusTemperature);
		compDelay(3);
		//delay(10000);
		LED0 = 0;
		COMP = 0;
		printf("Compressor Off! \r\n");
		compDelay(3);
		//delay(10000);*/

		//Actual Code//
		UpdateCurrentMeasurement();		//Get the latest Temp and Humidity Values.

		if(currentMeasurement.celsiusTemperature > 120 || currentMeasurement.percentHumidity > 80)
		{
			LED0 = 1;
			COMP = 1;
			printf("Compressor On! \r\n");
		}
		else if(currentMeasurement.celsiusTemperature < 100 || currentMeasurement.percentHumidity < 30)
		{
			LED0 = 0;
			COMP = 0;
			printf("Compressor Off! \r\n");
		}
		printf("Humidity is: %u\r\n", currentMeasurement.percentHumidity);
		printf("Temperature is: %u\r\n", currentMeasurement.celsiusTemperature);

		compDelay(3);
	}
}
// $[SiLabs Startup]
// [SiLabs Startup]$

unsigned int delay(long x) {
	long i, y;

	for (y = 0; y < x; y++) {
		for (i = 0; i < 310; i++) {
			_nop_();
		}
	}
	return 0;
}

void UpdateCurrentMeasurement(void) {
	uint32_t calculationHolder;

	// Reset the Temperature & Humidity Sensor.
	//ResetSensor();

	calculationHolder = (((uint32_t) 125) * MeasureAndReadHumidity());
	// Covert read value to percent humidity following formula in si7021 data sheet
	currentMeasurement.percentHumidity = (uint8_t)(
			(calculationHolder >> 16) - 6);

	// Covert read value to celsius temperature following formula in si7021 data sheet
	//calculationHolder = (((uint32_t) 17572) * ReadTemperature());	//Changed by Peter
	calculationHolder = (((uint32_t) 17572) * MeasureAndReadTemperature());
	calculationHolder = ((calculationHolder >> 16) - 4685);
	currentMeasurement.celsiusTemperature = (int16_t)(calculationHolder / 10);

	// Reset the Temperature & Humidity Sensor.
	//ResetSensor();

}

unsigned int compDelay(int u)
{
	int t;
	for(t = 0; t < u; t++)
	{
		delay(60000);
	}
	return 0;
}

